---
- name: Copy Running Config to NAS storage with dtm
  hosts: localhost
  tasks:
    - name: Get ansible date/time facts
      setup:
        filter: "ansible_date_time"
        gather_subset: "!all"
    - name: Store DTG as fact
      set_fact:
        DTG: "{{ ansible_date_time.date }}"
- hosts: all
  gather_facts: False
  collections:
    - arubanetworks.aoscx
  vars:
    ansible_connection: arubanetworks.aoscx.aoscx
    ansible_network_os: arubanetworks.aoscx.aoscx
  tasks:
    - name: Copy Running Config to NAS storage
      aoscx_backup_config:
        config_name: 'running-config'
        remote_output_file_tftp_path: 'tftp://10.70.128.32/run_config/{{ inventory_hostname }}_{{hostvars.localhost.DTG}}_runconfig.cli'
        config_type: 'cli'
        vrf: 'default'        